apps/front/models.py
from exts import db
import shortuuid
import enum
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class Follow(db.Model):
    __tablename__ = 'follow'

    follower_id = db.Column(db.String(100), db.ForeignKey('front_user.id'), primary_key=True)
    followed_id = db.Column(db.String(100), db.ForeignKey('front_user.id'), primary_key=True)

    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class FrontUser(db.Model):
    __tablename__ = 'front_user'

    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), unique=True, nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(40))
    realname = db.Column(db.String(20))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now)

    followers = db.relationship('Follow', foreign_keys=[Follow.followed_id], backref=db.backref('followed', lazy='joined'), lazy='dynamic', cascade='all, delete-orphan')
    followed = db.relationship('Follow', foreign_keys=[Follow.follower_id], backref=db.backref('follower', lazy='joined'), lazy='dynamic', cascade='all, delete-orphan')

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
        super(FrontUser, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpw):
        self._password = generate_password_hash(newpw)

    def check_password(self, rawpw):
        return check_password_hash(self.password, rawpw)

    def is_following(self, user):
        if user.id is None:
            return False
        else:
            return self.followed.filter_by(followed_id=user.id).first() is not None

    def is_followed_by(self, user):
        if user.id is None:
            return False
        else:
            return self.followers.filter_by(follower_id=user.id).first() is not None

    def follow(self, user):
        if not self.is_following(user):
            f = Follow(follower=self, followed=user)
            db.session.add(f)

    def unfollow(self, user):
        f = self.followed.filter_by(followed_id=user.id).first()
        if f:
            db.session.delete(f)

apps/front/forms.py
from ..forms import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import regexp, length, input_required, equal_to, ValidationError, email
from utils import bbscache

class SignInForm(BaseForm):

    telephone = StringField(validators=[regexp(r'1[345789]\d{9}', message='请输入格式正确的手机号')])
    sms_captcha = StringField(validators=[length(6, 6, message='请输入正确长度的短信验证码')])
    username = StringField(validators=[length(4, -1, message='用户名必须为4位及以上')])
    password1 = StringField(validators=[input_required(message='请输入密码')])
    password2 = StringField(validators=[equal_to('password1', message='两次密码不同')])
    graph_captcha = StringField(validators=[length(4, 4, message='请输入正确长度的图形验证码')])

    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        sms_captcha2 = bbscache.get(self.telephone.data)
        if not sms_captcha2 or sms_captcha.lower() != sms_captcha2.lower():
            raise ValidationError(message='短信验证码错误')

    def validate_graph_captcha(self, filed):
        graph_captcha = filed.data
        graph_captcha2 = bbscache.get(graph_captcha.lower())
        if not graph_captcha2:
            raise ValidationError(message='图形验证码错误')


class LoginForm(BaseForm):
    telephone = StringField(validators=[regexp(r'1[345789]\d{9}', message='请输入格式正确的手机号')])
    password = StringField(validators=[input_required(message='请输入密码')])

    remember_me = IntegerField()


class PostAddForm(BaseForm):
    title = StringField(validators=[input_required('请输入标题')])
    content = StringField(validators=[input_required('请输入内容')])
    board_id = IntegerField(validators=[input_required('请选择所属板块')])


class CommentAddForm(BaseForm):
    content = StringField(validators=[input_required(message='请输入评论内容')])
    post_id = IntegerField(validators=[input_required(message='没有传递帖子ID')])
    reply_to = IntegerField()


class AccountModifyForm(BaseForm):
    username = StringField()
    email = StringField()
    realname = StringField()
    signature = StringField()
    gender = StringField()
    avatar_url = StringField()


class SecurityForm(SignInForm):
    username = StringField()
    old_password = StringField(validators=[input_required('请输入原密码')])

    def validate_password1(self, field):
        password = field.data
        old_password = self.old_password.data
        if password == old_password:
            raise ValidationError('新密码不能和旧密码一致')

apps/common/views.py
from flask import Blueprint, jsonify, make_response, request
from utils import bbscache, restful
from utils.captcha import Captcha
from utils.aliyunsdk.aliyunsms import send_sms
from io import BytesIO
import qiniu
from .forms import SMSCaptchaForm
import random, json


bp = Blueprint('common', __name__, url_prefix='/common')


@bp.route('/')
def index():
    return 'common page'


@bp.route('/upload_qiniu/', methods=["GET", "POST"])
def upload_qiniu():
    access_key = 'SJzKzuxsqx4XPIZ44cfVmDJncqqX2HwaDkxT93tp'
    secret_key = 'AkmSBkAP_C1wEz8krwA5xfeDqN4R1gkWnfx5QqQZ'
    q = qiniu.Auth(access_key, secret_key)
    bucket = 'corz-cache'
    token = q.upload_token(bucket)
    return jsonify({"uptoken": token})


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    bbscache.set(text.lower(), text.lower())
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/sms_captcha/', methods=['POST'])
def sms_captcha():
    form = SMSCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        code = ''.join(random.sample([str(i) for i in range(10)], 6))
        result = send_sms(telephone, code)
        result = json.loads(result.decode())
        if result['Message'] == 'OK':
            bbscache.set(telephone, code, timeout=300)
            print('验证码：', code)
            return restful.success()
        else:
            return restful.params_error(message=result['Message'])
    else:
        return restful.params_error(message='参数错误')

apps/front/__init__.py
from .views import bp
import apps.front.hooks

apps/front/views.py
from flask import Blueprint, render_template, views, request, session, redirect, url_for, g, abort
from utils import restful, safe_utils
from .forms import SignInForm, LoginForm, PostAddForm, CommentAddForm, AccountModifyForm, SecurityForm
from .models import FrontUser
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPost
from exts import db
from .decorator import login_required
import config
from flask_paginate import get_page_parameter, Pagination


bp = Blueprint('front', __name__)


@bp.route('/')
def index():

    board_id = request.args.get('board_id', type=int, default=None)
    sort = request.args.get('sort', type=int, default=None)
    # 获取banner图信息及板块信息
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4).all()
    boards = BoardModel.query.all()
    # 获取界面页数，并设置从数据库中选择切片的索引
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page-1)*config.PER_PAGE
    end = start + config.PER_PAGE
    # 设置帖子排序方式
    # sort==1：先按有无加精，再按时间倒叙
    if sort == 1:
        obj = db.session.query(PostModel).outerjoin(HighlightPost).order_by(HighlightPost.id.desc(), PostModel.create_time.desc())
    # sort==2：先按点赞数，再按时间倒叙
    elif sort == 2:
        # obj = PostModel.query.outerjoin(like_relation).group_by(PostModel.id).order_by(db.func.count(like_relation).desc(), PostModel.create_time.desc())

        obj = PostModel.query.outerjoin(FrontUser).group_by(PostModel.id)
        print(obj)
        obj = obj.order_by(db.func.count(FrontUser.id).desc(), PostModel.create_time.desc())
    # sort==3：先按评论数，再按时间倒叙
    elif sort == 3:
        obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(db.func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    # 无sort参数：按时间倒叙
    else:
        obj = PostModel.query.order_by(PostModel.create_time.desc())
    # 安装板块筛选帖子，并根据页面索引切片
    if board_id:
        posts = obj.filter(PostModel.board_id == board_id).slice(start, end)
        total = PostModel.query.filter_by(board_id=board_id).count()
    else:
        posts = obj.slice(start, end)
        total = PostModel.query.count()

    pagination = Pagination(page=page, total=total, bs_version=3)
    content = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board_id': board_id
    }
    return render_template('front/index.html', **content)


@bp.route('/account/', methods=['POST', 'GET'])
@login_required
def account():
    if request.method == 'GET':
        return render_template('front/account.html')
    else:
        form = AccountModifyForm(request.form)
        if form.validate():
            # 获取用户信息的表单数据
            username = form.username.data
            email = form.email.data
            realname = form.realname.data
            signature = form.signature.data
            avatar_url = form.avatar_url.data
            # 从数据库中获取现在登陆的用户信息
            user = g.front_user
            # 判断用户是否提交了个人信息，若有则修改在数据库中
            if username:
                user.username = username
            if email:
                user.email = email
            if realname:
                user.realname = realname
            if signature:
                user.signature = signature
            user.avatar = avatar_url
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())


@bp.route('/security/', methods=['POST', 'GET'])
@login_required
def security():
    if request.method == 'GET':
        return render_template('front/security.html')
    else:
        form = SecurityForm(request.form)
        if form.validate():
            # 获取表单提交的新旧密码
            old_password = form.old_password.data
            password = form.password1.data
            # 获取登陆的用户信息
            user = g.front_user
            # 判断原密码是否和数据库一致， 若一致则修改
            if user.check_password(old_password):
                user.password = password
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error('原密码错误！')
        else:
            return restful.params_error(form.get_error())


@bp.route('/post/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    # 判断用户是否登陆
    try:
        user = g.front_user
    except:
        user = ''
    # 判断用户是否登陆，且改用户是否赞过这篇帖子
    if user and post.check_liker(user):
        like = True
    else:
        like = False

    content = {
        'post': post,
        'like': like
    }
    return render_template('front/post_detail.html', **content)


@bp.route('/add_post/', methods=['POST', 'GET'])
@login_required
def add_post():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/add_post.html', boards=boards)
    else:
        form = PostAddForm(request.form)
        if form.validate():
            title = form.title.data
            content = form .content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error('板块不存在')
            post = PostModel(title=title, content=content, board_id=board_id, author_id=g.front_user.id)
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())


@bp.route('/add_comment/', methods=['POST'])
@login_required
def add_comment():
    form = CommentAddForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content, post_id=post_id)
            comment.commenter = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        return restful.params_error('帖子不存在')
    return restful.params_error(form.get_error())


@bp.route('/delete_comment/', methods=['POST'])
@login_required
def delete_comment():
    comment_id = request.form.get('comment_id')
    if not comment_id:
        return restful.params_error('没有传递帖子ID')
    comment = CommentModel.query.get(comment_id)
    if not comment:
        return restful.params_error('该帖子不存在')
    if comment.commenter.id != g.front_user.id:
        return restful.params_error('呀！想删除其他人的帖子。不可能！')
    db.session.delete(comment)
    db.session.commit()
    return restful.success()


@bp.route('/inform_comment/', methods=['POST'])
@login_required
def inform_comment():
    pass


@bp.route('/like/', methods=["POST"])
@login_required
def add_like():
    post_id = request.form.get('post_id')
    print(post_id)
    if post_id:
        user = g.front_user
        post = PostModel.query.get(post_id)
        print(post)
        if post.check_liker(user):
            print(type(post.likers))
            post.likers.remove(user)
        else:
            post.likers.append(user)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error('没有传递帖子ID')


@bp.route('/personal/')
def personal():
    # 获取url的id参数，若无则认为是登陆者id，若都无则跳转到登陆界面
    try:
        user_id = request.args.get('id', g.front_user.id)
    except AttributeError:
        return redirect(url_for('front.login'))
    # 获取用户信息及关注者和被关注者信息
    user = FrontUser.query.get(user_id)
    if not user:
        abort(404)
    followed_lists = user.followed
    follower_lists = user.followers
    # 判断登陆用户和页面对应用户的关注关系
    relation = ''
    try:
        login_user = g.front_user
    except AttributeError:
        login_user = ''
    if login_user and login_user.is_following(user):
        relation = True

    content = {
        'user': user,
        'followed_lists': followed_lists,
        'follower_lists': follower_lists,
        'relation': relation
    }
    return render_template('front/personal.html', **content)


@bp.route('/add_follow_relation/', methods=['POST'])
@login_required
def add_followed_relation():
    # 获取登陆的用户
    follower = g.front_user
    # 获取要关注的用户ID
    followed_id = request.form.get('followed_id', None)
    # 判断被关注的用户是否存在
    if not followed_id:
        return restful.params_error('没有传递被关注者id')
    followed = FrontUser.query.get(followed_id)
    if not followed:
        return restful.params_error('用户不存在')
    # 判断用户直接是否已经操作关注关系，若有取消关注，无进行关注
    if follower.is_following(followed):
        follower.unfollow(followed)
    else:
        follower.follow(followed)
    db.session.commit()
    return restful.success()


class SignInView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safe_utils.is_safe_url(return_to):
            return render_template('front/sign_in.html', return_to=return_to)
        else:
            return render_template('front/sign_in.html')

    def post(self):
        form = SignInForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data

            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


class LoginView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.sign_in') and safe_utils.is_safe_url(return_to):
            return render_template('front/login.html', return_to=return_to)
        else:
            return render_template('front/login.html')

    def post(self):
        form = LoginForm(request.form)

templates/front/base.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ static('front/css/base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">my bbs</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ url_for('front.personal') }}">个人中心 <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="请输入关键字">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      {% if g.front_user %}
        <span id="login-tag" style="display:none" data-login="1"></span>
        <li class="dropdown">
          <a class="btn dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            {{ g.front_user.username }}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
            <li><a href="{{ url_for('front.account')}}" target="_blank">个人信息</a></li>
            <li><a href="{{ url_for('front.security') }}">安全设置</a></li>
            <li><a href="{{ url_for('front.logout') }}" target="_blank">注销</a></li>
          </ul>
        </li>
      {% else %}
        <li><a href="{{ url_for('front.login') }}">登陆</a></li>
        <li><a href="{{ url_for('front.sign_in') }}">注册</a></li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->


</nav>
    <div class="main-container">
            {% block body %}{% endblock %}
    </div>
</body>
</html>

templates/front/index.html
{% extends 'front/base.html' %}
{% from 'common/_macros.html' import static %}

{% block title -%}
    bbs
{%- endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->

          <div class="carousel-inner index-banner" role="listbox">
              {% for banner in banners %}
                {% if loop.first %}
                    <div class="item active">
                {% else %}
                    <div class="item">
                {% endif %}
                     <a href="{{ banner.link_url }}"><img src="{{ banner.image_url }}" alt="..."></a>
                    </div>
              {% endfor %}


          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="post-group">
            <ul class="post-list-head">
                <li class="active"><a href="{{ url_for('front.index', board_id=current_board_id) }} ">最新</a></li>
                <li><a href="{{ url_for('front.index', board_id=current_board_id, sort=1) }}">精华帖子</a></li>
                <li><a href="{{ url_for('front.index', board_id=current_board_id, sort=2) }}">点赞最多</a></li>
                <li><a href="{{ url_for('front.index', board_id=current_board_id, sort=3) }}">评论最多</a></li>
            </ul>
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="author-avatar-group">
                            <img src="{{ post.author.avatar or static('image/default_avatar.png') }}" >
                        </div>
                        <div class="post-info-group">
                            <p class="post-title">
                                <a href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                                {% if post.highlight %}
                                    <span class="label label-primary">精华</span>
                                {% endif %}
                            </p>
                            <p class="post-info">
                                <a href="{{ url_for('front.personal', id=post.author.id) }}">
                                    <span>作者：{{ post.author.username }}</span>
                                </a>

                                <span>发表时间：{{ post.create_time }}</span>
                                <span>评论：{{ post.comments|count }}</span>
                                <span>阅读数：0</span>
                                <span>点赞数：{{ post.likers|count }}</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div style="text-align: center">
                {{ pagination.links }}
            </div>
        </div>
    </div>

    <div class="sm-container">
        <div class="publish-box">
            <a href="{{ url_for('front.add_post') }}"><button class="btn btn-warning btn-block">发表帖子</button></a>
        </div>
        <div class="list-group">
            {% if current_board_id %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}

            {% for board in boards %}
                {% if current_board_id==board.id %}
                    <a href="{{ url_for('front.index', board_id = board.id) }}" class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for('front.index', board_id = board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}

            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/front/sign_in.html
{% extends 'front/sign_login_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title -%}
    bbs账号注册
{%- endblock %}

{% block header %}
        <script src="{{ static('front/js/sign_in.js') }}"></script>
        <link rel="stylesheet" href="{{ static('front/css/sign_in.css') }}">
{% endblock %}

{% block sign_content %}
    <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="telephone" placeholder="手机号">
                <span class="input-group-btn">
                    <button id="sms_captcha" class="btn btn-default">获取验证码</button>
                </span>
            </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图像验证码">
            <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" >
            </span>
        </div>
    </div>
    <div class="form-group">

        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="csrf-token" content="{{ csrf_token() }}">#}
{#    <title>bbs账号注册</title>#}
{#    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>#}
{#    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
{#    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>#}
{#    <script src="{{ static('front/js/sign_in.js') }}"></script>#}
{#    <script src="{{ static('common/zlparam.js') }}"></script>#}
{#    <script src="{{ static('common/zlajax.js') }}"></script>#}
{#    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">#}
{#    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>#}
{#    <script src="{{ static('common/sweetalert/xtalert.js') }}"></script>#}
{#    <link rel="stylesheet" href="{{ static('front/css/sign_in.css') }}">#}
{#</head>#}
{#<body>#}
{#    <div class="outer-box">#}
{#        <div class="logo_box"><a href="/"><img src="{{ static('front/bbs_logo.PNG') }}" ></a></div>#}
{#        <h2 class="page-title">bbs账号注册</h2>#}
{#        <div class="form-box">#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <input type="text" class="form-control" name="telephone" placeholder="手机号">#}
{#                    <span class="input-group-btn">#}
{#                        <button id="sms_captcha" class="btn btn-default">获取验证码</button>#}
{#                    </span>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <input type="text" class="form-control" name="username" placeholder="用户名">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <input type="password" class="form-control" name="password1" placeholder="密码">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <input type="password" class="form-control" name="password2" placeholder="确认密码">#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <input type="text" class="form-control" name="graph_captcha" placeholder="图像验证码">#}
{#                    <span class="input-group-addon captcha-addon">#}
{#                        <img id="captcha-img" class="captcha-img" src="{{ url_for('front.graph_captcha') }}" >#}
{#                    </span>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <span style="display: none" id="return-to-span">{{ return_to }}</span>#}
{#                <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</body>#}
{#</html>#}