apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class CMSPermission():
    #使用8位二进制形式表示CMS用户权限(1111 1111)
    ALL_PERMISSION = 0b11111111
    #1.访问者权限
    VISITOR =        0b00000001
    #2.管理帖子的权限
    POSTER =         0b00000010
    #3.管理评论的权限
    COMMENTER =      0b00000100
    #4.管理板块的权限
    BOARDER =        0b00001000
    #5.管理前台用户的权限
    FRONTER =        0b00010000
    #6.管理后台用户的权限
    CMSUSER =        0b00100000

cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id', db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('cms_user_id', db.ForeignKey('cms_user.id'), primary_key=True)
)

class CmsRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(40), nullable=False)
    permission = db.Column(db.Integer, default=CMSPermission.VISITOR)
    desc = db.Column(db.String(100))
    set_time = db.Column(db.DateTime, default=datetime.now)

    users = db.relationship('CmsUser', secondary=cms_role_user, backref='roles')

class CmsUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True)
    set_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

    @property
    def permission(self):
        all_permission = 0
        if not self.roles:
            return all_permission
        for role in self.roles:
            permission = role.permission
            all_permission = all_permission|permission
        return all_permission

    def has_permission(self, permission):
        return self.permission&permission == permission

    @property
    def is_developer(self):
        return self.has_permission(CMSPermission.ALL_PERMISSION)

apps/cms/forms.py
from wtforms import StringField, IntegerField
from wtforms.validators import email, input_required, equal_to, ValidationError
from ..forms import BaseForm
from utils import bbscache
from flask import g


class LoginFrom(BaseForm):
    email = StringField(validators=[email(message='请输入正确的邮箱地址'), input_required(message='请输入邮箱')])
    password = StringField(validators=[input_required(message='请输入密码')])
    remember = IntegerField()


class ResetpwdForm(BaseForm):
    old_password = StringField(validators=[input_required(message='请输入原密码')])
    new_password = StringField(validators=[input_required(message='请输入新密码')])
    new_password_repeat = StringField(validators=[equal_to('new_password', message='两次密码不一致')])


class ResetemailForm(BaseForm):
    email = StringField(validators=[email(message='请输入正确格式的邮箱’')])
    captcha = StringField(validators=[input_required(message='请输入验证码')])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha2 = bbscache.get(email)
        if not captcha2 or captcha.lower() != captcha2.lower():
            raise ValidationError('验证码不一致')

    def validate_email(self, field):
        email = field.data
        if email == g.cms_user.email:
            raise ValidationError('不能修改为相同的邮箱')


class BannerForm(BaseForm):
    name = StringField(validators=[input_required('请输入轮播图名称')])
    image_url = StringField(validators=[input_required('请输入图片链接')])
    link_url = StringField(validators=[input_required('请输入跳转链接')])
    priority = IntegerField()


class UpdataBannerForm(BannerForm):
    banner_id = IntegerField(validators=[input_required(message='id传递失败')])


class AddBoardForm(BaseForm):
    name = StringField(validators=[input_required(message='请输入板块名称')])

class UpdateBoardForm(AddBoardForm):
    board_id = IntegerField(validators=[input_required(message='没有提供板块ID')])

apps/cms/__init__.py
from .views import bp

import apps.cms.hooks

apps/cms/views.py
from flask import Blueprint, views, render_template, request, session, redirect, url_for, g
from .forms import LoginFrom, ResetpwdForm, ResetemailForm, BannerForm, UpdataBannerForm, AddBoardForm, UpdateBoardForm
from .models import CmsUser, CMSPermission
from ..models import BannerModel, BoardModel, PostModel, HighlightPost
from .decorator import login_required, permission_required
import config
from exts import db, mail
from utils import restful, bbscache
from flask_mail import Message
import string, random

bp = Blueprint('cms', __name__, url_prefix='/cms')

@bp.route('email_captcha')
def email_captcha():
    email = request.args.get('email')
    if not email:
        return restful.params_error('请输入邮箱参数')

    #set captcha
    source = list(string.ascii_letters)
    source.extend([str(i) for i in range(10)])
    captcha = ''.join(random.sample(source, 4))
    #send email
    message = Message('BBS邮箱验证', recipients=[email], body='your email captcha is {}'.format(captcha))
    try:
        mail.send(message)
    except:
        return restful.server_error('请稍后再试')
    bbscache.set(email, captcha)
    return restful.success()


@bp.route('/')
@login_required
def index():
    return render_template('cms/index.html')


@bp.route('/logout/')
@login_required
def logout():
    session.pop(config.CMS_USER_ID)
    return redirect(url_for('cms.cms_login'))


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/profile.html')


@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/banners.html', banners=banners)


@bp.route('/add_banner/', methods=['POST'])
@login_required
def add_banners():
    form = BannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/update_banner/', methods=['POST'])
@login_required
def updata_banners():
    form = UpdataBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('轮播图不存在')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/del_banner/', methods=['POST'])
@login_required
def del_banner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请传入轮播图ID')

    banner = BannerModel.query.get(banner_id)
    if banner:
        db.session.delete(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message='找不到该轮播图')


@bp.route('/posts/')
@permission_required(CMSPermission.POSTER)
@login_required
def posts():
    posts = PostModel.query.order_by(PostModel.create_time.desc()).all()
    return render_template('cms/posts.html', posts=posts)


@bp.route('/hl_post/', methods=['POST'])
@permission_required(CMSPermission.POSTER)
@login_required
def hl_post():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('没有传入帖子ID')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('该帖子不存在')
    highlight = HighlightPost()
    highlight.post = post
    db.session.add(post)
    db.session.commit()
    return restful.success()


@bp.route('/unhl_post/', methods=["POST"])
@permission_required(CMSPermission.POSTER)
@login_required
def unhl_post():
    post_id = request.form.get('post_id')
    print(post_id)
    if not post_id:
        return restful.params_error('没有传入帖子ID')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('该帖子不存在')
    highlight = HighlightPost.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()

@bp.route('/comments/')
@permission_required(CMSPermission.COMMENTER)
@login_required
def comments():
    return render_template('cms/comments.html')


@bp.route('/boards/')
@permission_required(CMSPermission.BOARDER)
@login_required
def boards():
    board_models = BoardModel.query.all()
    return render_template('cms/boards.html', boards=board_models)


@bp.route('/add_board/', methods=['POST'])
@permission_required(CMSPermission.BOARDER)
@login_required
def add_board():
    form = AddBoardForm(request.form)
    if form.validate():
        board_name = form.name.data
        board = BoardModel.query.filter_by(name=board_name).first()
        if not board:
            board = BoardModel(name=board_name)
            db.session.add(board)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('板块已存在')
    else:
        return restful.params_error(form.get_error())


@bp.route('/update_board/', methods=['POST'])
@permission_required(CMSPermission.BOARDER)
@login_required
def update_board():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        board_name = form.name.data
        board = BoardModel.query.get(board_id)
        if not board:
            return restful.params_error('该板块不存在')
        board.name = board_name
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(form.get_error())


@bp.route('/del_board/', methods=['POST'])
@permission_required(CMSPermission.BOARDER)
@login_required
def del_board():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.params_error('没有传递板块ID')
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error('该板块不存在')
    db.session.delete(board)
    db.session.commit()
    return restful.success()


@bp.route('/users/')
@permission_required(CMSPermission.FRONTER)
@login_required
def fuser_manage():
    return render_template('cms/fuser_manage.html')


@bp.route('/cmsuser_manage/')
@permission_required(CMSPermission.CMSUSER)
@login_required
def cuser_manage():
    return render_template('cms/cuser_manage.html')


@bp.route('/cmsrole_manage/')
@permission_required(CMSPermission.ALL_PERMISSION)
@login_required
def crole_manage():
    return render_template('cms/crole_manage.html')


@bp.route('/resetpwd/', methods=['GET', 'POST'])
@login_required
def resetpwd():
    if request.method == 'GET':
        return render_template('cms/resetpwd.html')
    else:
        form = ResetpwdForm(request.form)
        if form.validate():
            old_password = form.old_password.data
            new_password = form.new_password.data
            if g.cms_user.check_password(old_password):
                g.cms_user.password = new_password
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error(message='旧密码错误!')
        else:
            message = form.get_error()
            return restful.params_error(message=message)


class ResetemailView(views.MethodView):

    decorators = [login_required]

    def get(self):
        return render_template('cms/resetemail.html')

    def post(self):
        form = ResetemailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())


class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/login.html', message=message)

    def post(self):
        form = LoginFrom(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            cms_user = CmsUser.query.filter(CmsUser.email == email).first()
            if cms_user and cms_user.check_password(password):
                session[config.CMS_USER_ID] = cms_user.id
                if remember:
                    session.permanent = True
                return redirect(url_for('cms.index'))
            return self.get(message='用户名或密码错误')
        else:
            #print(form.errors)#form.errors可能是一个生成器
            message = form.errors
            return self.get(message=message)

bp.add_url_rule('/login/', endpoint='cms_login', view_func=LoginView.as_view('cms_login'))
bp.add_url_rule('/resetemail/', endpoint='resetemail', view_func=ResetemailView.as_view('resetemail'))

templates/cms/banners.html
{% extends 'cms/base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/banners.js') }}"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ static('common/zlqiniu.js') }}"></script>

{% endblock %}

{% block page_head %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>名称</th>
                <th>图片链接</th>
                <th>跳转链接</th>
                <th>优先级</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
                <tr data-id="{{ banner.id }}" data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


<!-- Modal -->
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="modal-close-btn"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
      </div>
      <div class="modal-body">
          <form action="" class="form-horizontal">
              <div class="form-group">
                  <label class="col-sm-2 control-label">名称:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">图片:</label>
                  <div class="col-sm-7">
                      <input type="text" class="form-control" name="image_url" placeholder="轮播图链接">
                  </div>
                  <button class="btn btn-info col-sm-2" id="upload-banner-btn">添加图片</button>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">跳转:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">权重:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="priority" placeholder="优先级">
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cms/base.html
{% from 'common/_macros.html' import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PythonBBS-CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>
                {% set user=g.cms_user %}
                <li class="nav-group banners-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if user.has_permission(CMSPermission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}
                {% if user.has_permission(CMSPermission.COMMENTER) %}
                    <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                {% endif %}
                {% if user.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPermission.FRONTER) %}
                    <li class="nav-group user-manage"><a href="{{ url_for('cms.fuser_manage') }}">前台用户管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cuser_manage') }}">CMS用户管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPermission.ALL_PERMISSION) %}
                   <li class="cmsrole-manage"><a href="{{ url_for('cms.crole_manage') }}">CMS组管理</a></li>
                {% endif %}
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_head %}
            {% endblock %}</h1>
            <div class="main_content">
                {% block content %}
                {% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/boards.html
{% extends 'cms/base.html' %}
{% from 'common/_macros.html' import static %}

{% block title -%}
    板块管理
{%- endblock %}

{% block head -%}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    <div class="top-box">
        <button class="btn btn-warning" id="add-board-btn">添加板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>板块名称</th>
                <th>帖子数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr data-id="{{ board.id }}" data-name="{{ board.name }}">
                    <td>{{ board.name }}</td>
                    <td>pass</td>
                    <td>{{ board.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
<!-- Modal -->
<div class="modal fade" id="board-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="modal-close-btn"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">添加板块</h4>
      </div>
      <div class="modal-body">
          <form action="" class="form-horizontal">
              <div class="form-group">
                  <label class="col-sm-2 control-label">名称:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" placeholder="板块名称">
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>
{%- endblock %}

templates/cms/comments.html
{% extends 'cms/base.html' %}

{% block title -%}
    评论管理
{%- endblock %}

{% block head -%}

{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    This is comment manage page
{%- endblock %}

templates/cms/crole_manage.html
{% extends 'cms/base.html' %}

{% block title -%}
    CMS组管理
{%- endblock %}

{% block head -%}

{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    This is CMS role manage page
{%- endblock %}

templates/cms/cuser_manage.html
{% extends 'cms/base.html' %}

{% block title -%}
    CMS用户管理
{%- endblock %}

{% block head -%}

{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    This is CMS user manage page
{%- endblock %}

templates/cms/fuser_manage.html
{% extends 'cms/base.html' %}

{% block title -%}
    前台用户管理
{%- endblock %}

{% block head -%}

{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    This is front user manage page
{%- endblock %}

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    My BBS
{% endblock %}

{% block page_head %}
    Welcome to my BBS
{% endblock %}

templates/cms/login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CMS LOGIN</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='cms/css/cms_login.css') }}" rel="stylesheet">


  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post">
          <input type="hidden"  name="csrf_token" value="{{ csrf_token() }}">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="remember" value="1"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
        {% if message %}
            <p class="text-center text-danger">{{ message }}</p>
        {% endif %}

    </div> <!-- /container -->

  </body>
</html>

templates/cms/posts.html
{% extends 'cms/base.html' %}
{% from 'common/_macros.html' import static %}

{% block title -%}
    帖子管理
{%- endblock %}

{% block head -%}
    <script src="{{ static('cms/js/posts.js') }}"></script>
{%- endblock %}

{% block page_head -%}
    {{ self.title() }}
{%- endblock %}

{% block content -%}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>所属板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr data-id="{{ post.id }}" data-highlight="{{ '1' if post.highlight else '0' }}">
                    <td><a target="_blank" href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a></td>
                    <td>{{ post.create_time }}</td>
                    <td>{{ post.board.name }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% if post.highlight %}
                        <button class="btn btn-default btn-xs edit-banner-btn highlight-btn">
                            取消加精
                        </button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">
                            删除
                        </button>
                        {% else %}
                        <button class="btn btn-default btn-xs edit-banner-btn highlight-btn">
                            加精
                        </button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">
                            删除
                        </button>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{%- endblock %}

templates/cms/profile.html
{% extends 'cms/base.html' %}

{% block title %}
个人信息
{% endblock %}

{% block page_head %}
 {{ self.title() }}
{% endblock %}

{% block content %}
{% set user=g.cms_user %}
<table class="table table-bordered">
    <tbody>
        <tr>
            <td>username</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>email</td>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <td>role</td>
            <td>
            {% for role in user.roles %}
               {{ role.name }}
                {% if not loop.last %}
                    ,
                {% endif %}
            {% endfor %}
            </td>
        </tr>
        <tr>
            <td>jurisdiction</td>
            <td>
                {% for role in user.roles %}
                    {{ role.desc }}
                    {% if not loop.last %}
                        ;
                    {% endif %}
                {% endfor %}

            </td>
        </tr>
        <tr>
            <td>join time</td>
            <td>{{ user.set_time }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/cms/resetemail.html
{% extends 'cms/base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    修改邮箱
{% endblock %}

{% block page_head %}
    {{ self.title() }}
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/resetemail.js') }}"></script>
{% endblock %}

{% block content %}
    <form action="" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-container">
            <div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" name="email" placeholder="请输入邮箱">
                    <div class="input-group-addon" style="cursor: pointer" id="captcha-btn">发送验证码</div>
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="captcha" placeholder="验证码">
            </div>
        </div>
        <button type="submit" class="btn btn-primary" id="submit">确认修改</button>
    </form>
{% endblock %}